---
certs_ca_certificate_path: /etc/etcd-ca
certs_etcd_certificate_path: /etc/etcd/tls
certs_ca_bundle_path: '{{ certs_etcd_certificate_path }}/etcd-ca.pem'
certs_etcd_env: '{{ etcd_mgr_env }}'
certs_output_path:  '{{ playbook_dir }}/output/{{ certs_etcd_env }}'
certs_output_bundle_file_name: etcd-ca-bundle.pem
certs_output_bundle_file: '{{ certs_output_path }}/{{ certs_output_bundle_file_name }}'
certs_ca_certificate_root_cname: 'etcd'
certs_ca_certificate_root_key_file: '{{ certs_ca_certificate_path }}/ca-root.key'
certs_ca_certificate_root_crt_file: '{{ certs_ca_certificate_path }}/ca-root.pem'
certs_ca_certificate_root_csr_file: '{{ certs_ca_certificate_path }}/ca-root.csr'
certs_ca_root_key_passkey: '{{ vault_certs_ca_root_key_passkey }}' 
certs_ca_key_passkey: '{{ vault_certs_ca_key_passkey }}' 
certs_ca_root_ownca_not_after: +3652d
certs_ca_certificate_set_immutable: false
certs_etcd_key_file: '{{ certs_etcd_certificate_path }}/etcd-node.key'
certs_etcd_crt_file: '{{ certs_etcd_certificate_path }}/etcd-node.pem'
certs_etcd_csr_file: '{{ certs_etcd_certificate_path }}/etcd-node.csr'
certs_etcd_csr_forced: false
certs_etcd_common_name: '{{ inventory_hostname }}'
certs_etcd_locality_name: 'etcd-node'
certs_etcd_organization_name: 'etcd mtp'
certs_etcd_organizational_unit_name: 'etcd cluster'
certs_etcd_client_locality_name: 'etcd-client'
certs_etcd_client_organization_name: 'etcd mtp'
certs_etcd_client_organizational_unit_name: 'etcd cluster'
certs_etcd_ownca_not_after: +365d
certs_etcd_cname: etcd-node-a
certs_etcd_ca_server: seed
certs_etcd_group: etcd
certs_etcd_owner: etcd
certs_etcd_client_group: ubuntu
certs_etcd_client_owner: ubuntu
certs_etcd_client_ca_server: '{{ certs_etcd_ca_server }}'
certs_etcd_client_domain: eu-central-1.compute.internal
certs_etcd_sans:
  - DNS:localhost
  - DNS:etcd-node-a
  - DNS:etcd-node-b
  - DNS:etcd-node-c
  - IP:127.0.0.1
  - IP:10.0.2.237
  - IP:10.0.2.188
  - IP:10.0.2.160 
certs_etcd_client_certificate_path: '{{ certs_etcd_certificate_path }}'
certs_etcd_client_certs:
  - name: etcd-tenant-a
    cname: etcd-tenant-a 
  - name: etcd-tenant-b
    cname: etcd-tenant-b
certs_etcd_client_csr_forced: false
certs_etcd_client_ownca_not_after: +365d 
