---
etcd_users_node_iface: '{{ etcd_node_iface }}'
etcd_users_container: etcd
etcd_users_cacert_file: /etc/etcd/tls/etcd-ca.pem 
etcd_user_root_password: '{{ vault_etcd_user_root_password }}' 
etcd_roles_list:
  - role: atenant
    prefix: atenant 
  - role: btenant
    prefix: btenant 
etcd_users_list:
  - user: auser
    role: atenant
    password: '{{ vault_etcd_user_auser_password }}' 
  - user: buser
    role: btenant
    password: '{{ vault_etcd_user_buser_password }}' 

