---
etcd_install_files_path: /var/tmp/etcd-install
etcd_data_dir: /var/lib/etcd
etcd_dir: /var/etcd
etcd_tls_dir: /etc/etcd/tls
etcd_systemd_unit_file: /etc/systemd/system/etcd.service
etcd_uid: 1001
etcd_release: v3.5.18
etcd_user: etcd
etcd_group: etcd
etcd_token: '{{ vault_etcd_token }}'
enable_tls: true
etcd_protocol: '{% if enable_tls %}https{% else %}http{% endif %}' 
etcd_ca_file: '{{ etcd_tls_dir }}/etcd-ca.pem' 
etcd_peer_trusted_ca_file: '{{ etcd_tls_dir }}/etcd-ca.pem' 
etcd_cert_file: '{{ etcd_tls_dir }}/etcd-node.pem' 
etcd_key_file: '{{ etcd_tls_dir }}/etcd-node.key' 
etcd_peer_cert_file: '{{ etcd_tls_dir }}/etcd-node.pem' 
etcd_peer_key_file: '{{ etcd_tls_dir }}/etcd-node.key' 
etcd_peer_client_cert_auth: true 
etcd_client_cert_auth: false
etcd_nodes:
  - name: etcd-node-a
    ipv4: 10.0.2.160
  - name: etcd-node-b
    ipv4: 10.0.2.237  
  - name:  etcd-node-c
    ipv4: 10.0.2.188
etcd_node_idx: 0
etcd_node_iface: eth1
etcd_node_name: '{{ etcd_nodes[etcd_node_idx].name }}'
etcd_cluster: '{{ etcd_nodes[0].name }}={{ etcd_protocol }}://{{ etcd_nodes[0].ipv4 }}:2380,{{ etcd_nodes[1].name }}={{ etcd_protocol }}://{{ etcd_nodes[1].ipv4 }}:2380,{{ etcd_nodes[2].name }}={{ etcd_protocol }}://{{ etcd_nodes[2].ipv4 }}:2380'
